# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Movement.create(name: "Back Squat", style: "Powerlifting", target_area: "Lower Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=ultWZbUMPL8&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=3")
Movement.create(name: "Snatch", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=9xQp2sldyts&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=16")
Movement.create(name: "Deadlift", style: "Powerlifting", target_area: "Lower Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=op9kVnSso6Q&index=40&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Front Squat", style: "Weightifting", target_area: "Full Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=m4ytaCJZpl0&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=2")
Movement.create(name: "Overhead Squat", style: "Olympic Weightifting", target_area: "Full Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=RD_vUnqwqqI&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=4")
Movement.create(name: "Sumo Deadlift", style: "Powerlifting", target_area: "Lower Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=wQHSYDSgDn8&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=38")
Movement.create(name: "Sumo Deadlift High Pull", style: "Weightlifting", target_area: "Full Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=o6QniJ9FaGA&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=39")
Movement.create(name: "Dumbbell Deadlift", style: "Odd Object", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=Uo8mJamU3Uw")
Movement.create(name: "Press", style: "Weightlifting", target_area: "Upper Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=xe19t2_6yis&index=29&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Bench Press", style: "Powerlifting", target_area: "Upper Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=XSza8hVTlmM&index=77&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Push Press", style: "Olympic Weightlifting", target_area: "Upper Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=X6-DMh-t4nQ&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=31")
Movement.create(name: "Dumbbell Press", style: "Odd Object", target_area: "Upper Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=AqzDJHxynwo&index=28&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Dumbbell Push Press", style: "Odd Object", target_area: "Upper Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=MqvN10OF5fo&index=30&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Clean", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=EKRiW9Yt3Ps&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=27")
Movement.create(name: "Power Clean", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Moderate", video_url: "/www.youtube.com/watch?v=GVt4uQ0sDJE&index=25&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Clean & Jerk", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=9HyWjAk7fhY")
Movement.create(name: "Dumbbell Clean", style: "Odd Object", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=CUaxieWW0tw&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=22")
Movement.create(name: "Hang Clean", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=TjTEOme9fvw&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=26")
Movement.create(name: "Hang Power Clean", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=_iUFG1-H7d0&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=23")
Movement.create(name: "Hang Clean & Jerk", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=zedsLalfrss")
Movement.create(name: "Power Snatch", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=tuOiNeTvLJs")
Movement.create(name: "Hang Snatch", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=oTlSsPZaewg&index=15&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Hang Power Snatch", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=8AyTzORaBM8&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=13")
Movement.create(name: "Dumbbell Snatch", style: "Odd Object", target_area: "Full Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=9520DJiFmvE&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=10")
Movement.create(name: "Jerk", style: "Olympic Weightlifting", target_area: "Upper Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=V-hKuAfWNUw&index=33&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Kettlebell Swing", style: "Odd Object", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=vdezTMulJ-k&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=37")
Movement.create(name: "Kettlebell Turkish Get-up", style: "Odd Object", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=-_zTytmHM94&index=58&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Kettlebell Goblet Squat", style: "Odd Object", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=gXjNTLSVvGM")
Movement.create(name: "Rope Climb", style: "Gymnastics", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=qFE7pgOrj5w")
Movement.create(name: "Back Extension", style: "Accessory", target_area: "Core", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=RDNIPcmP5vs&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=74")
Movement.create(name: "Good Morning", style: "Accessory", target_area: "Posterior", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=ud6ZFpjIc-g")
Movement.create(name: "Box Jump", style: "Calisthenics", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=52r_Ul5k03g&index=76&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Box Step-up", style: "Calisthenics", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=dw8xOAr6RuM")
Movement.create(name: "Lunge", style: "Calisthenics", target_area: "Lower Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=L8fvypPrzzs&index=63&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Jump Lunge", style: "Calisthenics", target_area: "Lower Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=grID4CMcPdA")
Movement.create(name: "L-Sit", style: "Gymnastics", target_area: "Core", rep_range: "Minutes", video_url: "//www.youtube.com/watch?v=DemH-mw1O9I&index=62&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Sit-up", style: "Calisthenics", target_area: "Core", rep_range: "High", video_url: "//www.youtube.com/watch?v=_HDZODOx7Zw&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=59")
Movement.create(name: "Hollowrock", style: "Gymnastics", target_area: "Core", rep_range: "High", video_url: "//www.youtube.com/watch?v=p7j02V1fIzU&index=60&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Archrock", style: "Gymnastics", target_area: "Core", rep_range: "High", video_url: "//www.youtube.com/watch?v=F0l-p4bHJtE")
Movement.create(name: "Knees-to-Elbow", style: "Gymnastics", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=pcw3Rb4Lh7A")
Movement.create(name: "Toes-to-Bar", style: "Gymnastics", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=_03pCKOv4l4&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=47")
Movement.create(name: "Pushup", style: "Calisthenics", target_area: "Upper Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=_l3ySVKYVJ8&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=41")
Movement.create(name: "Strict Pull-up", style: "Gymnastics", target_area: "Upper Body", rep_range: "Low", video_url: "/www.youtube.com/watch?v=aAggnpPyR6E&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=49")
Movement.create(name: "Kipping Pull-up", style: "Gymnastics", target_area: "Upper Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=r45xLlH7r_M&index=50&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Chest-to-Bar Pull-up", style: "Gymnastics", target_area: "Upper Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=p9Stan68FYM&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=53")
Movement.create(name: "Dip", style: "Gymnastics", target_area: "Upper Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=eERwCQHZqfA&index=45&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Ring Dip", style: "Gymnastics", target_area: "Upper Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=Vt0lO4jpIDo&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=46")
Movement.create(name: "Handstand Push-Up", style: "Gymnastics", target_area: "Upper Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=hvoQiF0kBI8&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=44")
Movement.create(name: "Muscle-Up", style: "Gymnastics", target_area: "Upper Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=rtF51pQB6Wc")
Movement.create(name: "Bar Muscle-Up", style: "Gymnastics", target_area: "Upper Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=OCg3UXgzftc&index=55&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Burpee", style: "Calisthenics", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=TU8QYVW0gDU&index=57&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Dumbbell Thruster", style: "Odd Object", target_area: "Full Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=M5gEwLTtWbg&index=6&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Thruster", style: "Weightlifting", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=aea5BGj9a8Y&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G&index=7")
Movement.create(name: "Wallball", style: "Odd Object", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=fpUD0mcFp_0&index=5&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Ball Slam", style: "Odd Object", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=7gLEmS4nwi0")
Movement.create(name: "Burpee-Pullup", style: "Calisthenics", target_area: "Full Body", rep_range: "Moderate", video_url: "//www.youtube.com/watch?v=IcnxbHXu3Vc")
Movement.create(name: "Run", style: "Cardio", target_area: "Full Body", rep_range: "Meters", video_url: nil)
Movement.create(name: "Row", style: "Cardio", target_area: "Full Body", rep_range: "Meters", video_url: "//www.youtube.com/watch?v=S7HEm-fd534&index=75&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Double Under", style: "Cardio", target_area: "Full Body", rep_range: "High", video_url: "//www.youtube.com/watch?v=-tF3hUsPZAI&index=69&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")
Movement.create(name: "Plank Hold", style: "Gymnastics", target_area: "Full Body", rep_range: "Minutes", video_url: "//www.youtube.com/watch?v=v2-ltbaTGtE")
Movement.create(name: "Broad Jump", style: "Parkour", target_area: "Lower Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=MwiI72uFzNI")
Movement.create(name: "Bear Crawl", style: "Parkour", target_area: "Full Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=2yAWjVCT1VQ")
Movement.create(name: "Wall Walk", style: "Parkour", target_area: "Upper Body", rep_range: "Low", video_url: "//www.youtube.com/watch?v=2TnX8j29tRY&index=79&list=PLBrgqsGCyn2xQVBgDaemdoK8TJlgSpX0G")


User.create!(name: "Khal Drogo", email: "sexy@af.com", email_confirmation: "sexy@af.com", password: "sexy", password_confirmation: "sexy")
User.create!(name: "George Jetson", email: "george@george.com", email_confirmation: "george@george.com", password: "george", password_confirmation: "george")
User.create!(name: "Hector Projector", email: "hector@hector.com", email_confirmation: "hector@hector.com", password: "hector", password_confirmation: "hector")
