# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Workout.destroy_all

Movement.create(name: "Back Squat", style: "Powerlifting", target_area: "Lower Body", rep_range: "Moderate")
Movement.create(name: "Snatch", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Pull-up", style: "Gymnastics", target_area: "Upper Body", rep_range: "High")
Movement.create(name: "Situp", style: "Calisthenics", target_area: "Core", rep_range: "High")
Movement.create(name: "Deadlift", style: "Powerlifting", target_area: "Lower Body", rep_range: "Moderate")
Movement.create(name: "Front Squat", style: "Weightifting", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Overhead Squat", style: "Olympic Weightifting", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Sumo Deadlift", style: "Powerlifting", target_area: "Lower Body", rep_range: "Low")
Movement.create(name: "Sumo Deadlift High Pull", style: "Weightlifting", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Dumbbell Deadlift", style: "Odd Object", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Romanian Deadlift", style: "Weightlifting", target_area: "Lower Body", rep_range: "Low")
Movement.create(name: "Single-Leg Deadlift", style: "Weightlifting", target_area: "Lower Body", rep_range: "Low")
Movement.create(name: "Snatch Grip Deadlift", style: "Weightlifting", target_area: "Full Body", rep_range: "Low")
Movement.create(name: "Press", style: "Weightlifting", target_area: "Upper Body", rep_range: "Low")
Movement.create(name: "Bench Press", style: "Powerlifting", target_area: "Upper Body", rep_range: "Moderate")
Movement.create(name: "Dumbbell Press", style: "Odd Object", target_area: "Upper Body", rep_range: "Low")
Movement.create(name: "Dumbbell Push Press", style: "Odd Object", target_area: "Upper Body", rep_range: "Moderate")
Movement.create(name: "Clean", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Power Clean", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Clean & Jerk", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Low")
Movement.create(name: "Dumbbell Clean", style: "Odd Object", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Hang Clean", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Hang Power Clean", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Hang Clean & Jerk", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Power Snatch", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Hang Snatch", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Hang Power Snatch", style: "Olympic Weightlifting", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Dumbbell Snatch", style: "Odd Object", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Jerk", style: "Olympic Weightlifting", target_area: "Upper Body", rep_range: "Moderate")
Movement.create(name: "Kettlebell Swing", style: "Odd Object", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Kettlebell Turkish Get-up", style: "Odd Object", target_area: "Full Body", rep_range: "Low")
Movement.create(name: "Kettlebell Goblet Squat", style: "Odd Object", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Rope Climb", style: "Gymnastics", target_area: "Full Body", rep_range: "Low")
Movement.create(name: "Back Extension", style: "Accessory", target_area: "Core", rep_range: "Moderate")
Movement.create(name: "Good Morning", style: "Accessory", target_area: "Posterior", rep_range: "Moderate")
Movement.create(name: "Box Jump", style: "Calisthenics", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Box Step-up", style: "Calisthenics", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Lunge", style: "Calisthenics", target_area: "Lower Body", rep_range: "High")
Movement.create(name: "Jump Lunge", style: "Calisthenics", target_area: "Lower Body", rep_range: "High")
Movement.create(name: "L-Sit", style: "Gymnastics", target_area: "Core", rep_range: "Minutes")
Movement.create(name: "Sit-up", style: "Calisthenics", target_area: "Core", rep_range: "High")
Movement.create(name: "Hollowrock", style: "Gymnastics", target_area: "Core", rep_range: "High")
Movement.create(name: "Archrock", style: "Gymnastics", target_area: "Core", rep_range: "High")
Movement.create(name: "Knees-to-Elbow", style: "Gymnastics", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Toes-to-Bar", style: "Gymnastics", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Pushup", style: "Calisthenics", target_area: "Upper Body", rep_range: "High")
Movement.create(name: "Strict Pull-up", style: "Gymnastics", target_area: "Upper Body", rep_range: "Low")
Movement.create(name: "Kipping Pull-up", style: "Gymnastics", target_area: "Upper Body", rep_range: "High")
Movement.create(name: "Chest-to-Bar Pull-up", style: "Gymnastics", target_area: "Upper Body", rep_range: "High")
Movement.create(name: "Dip", style: "Gymnastics", target_area: "Upper Body", rep_range: "Moderate")
Movement.create(name: "Ring Dip", style: "Gymnastics", target_area: "Upper Body", rep_range: "Moderate")
Movement.create(name: "Handstand Push-Up", style: "Odd Object", target_area: "Upper Body", rep_range: "Moderate")
Movement.create(name: "Muscle-Up", style: "Gymnastics", target_area: "Upper Body", rep_range: "Low")
Movement.create(name: "Bar Muscle-Up", style: "Gymnastics", target_area: "Upper Body", rep_range: "Moderate")
Movement.create(name: "Burpee", style: "Calisthenics", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Dumbbell Thruster", style: "Odd Object", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Thruster", style: "Weightlifting", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Wallball", style: "Odd Object", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Ball Slam", style: "Odd Object", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Burpee-Pullup", style: "Calisthenics", target_area: "Full Body", rep_range: "Moderate")
Movement.create(name: "Run", style: "Cardio", target_area: "Full Body", rep_range: "Meters")
Movement.create(name: "Row", style: "Cardio", target_area: "Full Body", rep_range: "Meters")
Movement.create(name: "Double Under", style: "Cardio", target_area: "Full Body", rep_range: "High")
Movement.create(name: "Plank Hold", style: "Gymnastics", target_area: "Full Body", rep_range: "Minutes")
Movement.create(name: "Broad Jump", style: "Parkour", target_area: "Lower Body", rep_range: "Low")
Movement.create(name: "Bear Crawl", style: "Parkour", target_area: "Full Body", rep_range: "Low")
Movement.create(name: "Wall Climb", style: "Parkour", target_area: "Upper Body", rep_range: "Low")


User.create(name: "Khal Drogo", email: "sexy@af.com", password: "sexy", password_confirmation: "sexy")
User.create(name: "Sally Jensen", email: "sally@sally.com", password: "sally", password_confirmation: "sally")
User.create(name: "Bobby Bains", email: "bobby@bobby.com", password: "bobby", password_confirmation: "bobby")
User.create(name: "George Jetson", email: "george@george.com", password: "george", password_confirmation: "george")
User.create(name: "Hector Projector", email: "hector@hector.com", password: "hector", password_confirmation: "hector")
